spring:
  application:
    name: ticket-system
  profiles.active: development

---
spring:
  config:
    activate:
      on-profile:
        - development
zshop.db:
  url: jdbc:mysql://  url : #please enter db url
  username: root
  password: password
  driverClassName: Class.forName("com.mysql.cj.jdbc.Driver");

  
server:
  port: 4101
  servlet:
    context-path: "/${spring.application.name}"
 
---
spring:
  config:
    activate:
      on-profile:
        - uat
zshop.db:
  url: jdbc:mysql://  url : #please enter db url
  username: root
  password: password
  driverClassName: com.mysql.jdbc.Driver
  
  
server:
  port: 4101
  servlet:
    context-path: "/${spring.application.name}"
---
spring:
  config:
    activate:
      on-profile:
        - production
  
zshop.db:
  url: jdbc:mysql://#please enter db url
  username: root
  password: password
  driverClassName: com.mysql.jdbc.Driver
              
  
server:
  port: 4101
  servlet:
    context-path: "/${spring.application.name}"
---
spring:
  config:
    activate:
      on-profile:
        - docker
        
zshop.db:
  url : #please enter db url
  username: root
  password: password
  driverClassName: com.mysql.jdbc.Driver
          
  
server:
  port: 4101
  servlet:
    context-path: "/${spring.application.name}"

--------------------------
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.url= jdbc:mysql://localhost:3306/myDb
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
